### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by grupohernandezalba** [JorgeAndreiArias/Geo-Vue#1]
Muy bien @JorgeAndreiArias si pudieras implementar la opción de EDITAR productos

![Captura de Pantalla 2020-03-12 a la(s) 21 17 59](https://user-images.githubusercontent.com/14998558/76586663-287fc680-64a7-11ea-92a1-42836a3589d9.png)

**Comment by JorgeAndreiArias** [comment]
Listo, añadida la funcionalidad de editar
[image: image.png]

**Comment by grupohernandezalba** [comment]
Muy bien , si pudieras poner la captura de nombre, código y botón de agregar en una sola línea vas a ahorrar espacio. Prueba en celulares.

**Comment by JorgeAndreiArias** [comment]
Tabla totalmente responsiva y botones ajustados a la misma columna dentro de la tabla
![image](https://user-images.githubusercontent.com/37642617/76647281-23139200-6522-11ea-95f9-bec62b3b5e8e.png)
